ipv6: false
mixed-port: 7890
bind-address: "*"
mode: rule
log-level: silent
find-process-mode: off
disable-keep-alive: true
keep-alive-idle: 60
keep-alive-interval: 10
dns: 
  enable: true
  cache-algorithm: arc
  ipv6: false
  listen: 0.0.0.0:5350
  proxy-server-nameserver: 
    - https://223.6.6.6/dns-query
  enhanced-mode: fake-ip
  fake-ip-filter-mode: whitelist
  fake-ip-filter: 
    - "mtalk.google.com"
    - "+.vaultwarden.net"
    - "rule-set: DM_ITL"
  fallback: []
rule-providers:
  DM_CHN:
    proxy: DIRECT
    url: https://hub.gitmirror.com/github.com/MetaCubeX/meta-rules-dat/blob/meta/geo-lite/geosite/cn.mrs
    type: http
    format: mrs
    behavior: domain
    path: ./DM_CHN.mrs
  DM_ITL:
    proxy: DIRECT
    url: https://hub.gitmirror.com/github.com/MetaCubeX/meta-rules-dat/blob/meta/geo-lite/geosite/proxy.mrs
    type: http
    format: mrs
    behavior: domain
    path: ./DM_ITL.mrs
  IP_LAN:
    proxy: DIRECT
    url: https://hub.gitmirror.com/github.com/MetaCubeX/meta-rules-dat/blob/meta/geo/geoip/private.mrs
    type: http
    format: mrs
    behavior: ipcidr
    path: ./IP_LAN.mrs
  IP_CHN:
    proxy: DIRECT
    url: https://hub.gitmirror.com/github.com/MetaCubeX/meta-rules-dat/blob/meta/geo/geoip/cn.mrs
    type: http
    format: mrs
    behavior: ipcidr
    path: ./IP_CHN.mrs
######### https://raw.githubusercontent.com/odys2061/subc/refs/heads/major/conf.txt
######### https%3A%2F%2Fraw.githubusercontent.com%2Fodys2061%2Fsubc%2Frefs%2Fheads%2Fmajor%2Fconf.txt
