[custom]
clash_rule_base=https://raw.githubusercontent.com/odys2061/subc/major/conf.ini
custom_proxy_group=PROXY`fallback`.*`http://1.1.1.1/generate_204`2400,12,120
include_remarks=(Canada)
ruleset=PROXY,[]DOMAIN,mtalk.google.com
ruleset=PROXY,[]DOMAIN-SUFFIX,vaultwarden.net
ruleset=DIRECT,[]DOMAIN,connectivitycheck.gstatic.com
ruleset=DIRECT,[]DOMAIN-SUFFIX,msftncsi.com
ruleset=DIRECT,[]DOMAIN-SUFFIX,msftconnecttest.com
ruleset=PROXY,[]RULE-SET,DM_ITL
ruleset=DIRECT,[]RULE-SET,DM_CHN
ruleset=PROXY,[]AND,((DST-PORT,80),(NOT,((RULE-SET,IP_LAN))),(NOT,((RULE-SET,IP_CHN))))
ruleset=PROXY,[]AND,((DST-PORT,443),(NOT,((RULE-SET,IP_CHN))))
ruleset=DIRECT,[]MATCH
######### https://raw.githubusercontent.com/odys2061/subc/major/gen.ini
######### https%3A%2F%2Fraw.githubusercontent.com%2Fodys2061%2Fsubc%2Frefs%2Fheads%2Fmajor%2Fgen.ini
